第2階段，第1週作業-許軒豪
HSUHAOBM/taipei-day-trip-website pull request #2
Opened 2021-04-24 15:43 UTC by HSUHAOBM

第2階段，第1週作業-許軒豪
再麻煩老師檢查，謝謝

http://3.18.249.2:3000/attraction/1
http://3.18.249.2:3000/api/attractions?page=1
http://3.18.249.2:3000/api/attractions?keyword=大安森林公園

2021-04-24 16:54 UTC, cwpeng requested changes
1. 我們的頁數是以 0 為第一頁，請調整一下。
2. 如果是最後一頁，nextPage 請回應 null，例如：
http://3.18.249.2:3000/api/attractions?page=27
回應中的 nextPage 就應該是 null
3. 關鍵字搜尋是對景點的名稱做查詢，只要包含關鍵字就算數，不用完全一樣，而且也同樣要做分頁處理，你可以測試搜尋【臺北】，應該會有好幾頁的資料，一樣可以分成第 0 頁，第 1 頁這樣取得。

2021-04-24 20:22 UTC, HSUHAOBM commented
老師好，API修正完成，謝謝

http://3.18.249.2:3000/api/attractions?page=26
http://3.18.249.2:3000/api/attractions?page=0

http://3.18.249.2:3000/api/attractions?page=0&keyword=台
http://3.18.249.2:3000/api/attractions?page=1&keyword=台

http://3.18.249.2:3000/attraction/1

2021-04-25 06:12 UTC, cwpeng approved these changes
Good Changes.

2021-04-25 08:19 UTC, HSUHAOBM commented
謝謝老師，這週學到蠻多新東西，會找時間多熟悉熟悉!!

2021-04-25 08:22 UTC, merged